apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: neighbors.named-data.net
spec:
  group: named-data.net
  names:
    categories: []
    kind: Neighbor
    plural: neighbors
    shortNames:
    - nb
    singular: neighbor
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Neighbor references a public face of an external NDN network
        properties:
          spec:
            properties:
              network:
                description: Name of the local Network CR this neighbor applies to
                type: string
              uri:
                description: Public URI of the neighbor network (e.g., tcp://host:port)
                type: string
            required:
            - network
            - uri
            type: object
        required:
        - spec
        title: Neighbor
        type: object
    served: true
    storage: true
    subresources: {}
